spring:
  application:
    name: ${artifactId}
    version: ${version}
  jmx.enabled: true
  data:
    mongodb:
      uri: \${MONGODB_URI:mongodb://localhost:27017}
      database: \${MONGODB_DBNAME:p4pa}
      # custom configured properties
      config:
        connectionPool:
          maxSize: \${MONGODB_CONNECTIONPOOL_MAX_SIZE:100}
          minSize: \${MONGODB_CONNECTIONPOOL_MIN_SIZE:0}
          maxWaitTimeMS: \${MONGODB_CONNECTIONPOOL_MAX_WAIT_MS:120000}
          maxConnectionLifeTimeMS: \${MONGODB_CONNECTIONPOOL_MAX_CONNECTION_LIFE_MS:0}
          maxConnectionIdleTimeMS: \${MONGODB_CONNECTIONPOOL_MAX_CONNECTION_IDLE_MS:120000}
          maxConnecting: \${MONGODB_CONNECTIONPOOL_MAX_CONNECTING:2}


rest-client:
  backend-io-manage:
    service:
      base-url: \${IO_MANAGE_BACKEND_SERVICE_BASE_URL:}
      subscriptionKey: \${IO_BACKEND_SERVICE_SUBSCRIPTION_API_KEY:}

management:
  endpoint:
    health:
      probes.enabled: true
      group:
        readiness.include: "*"
        liveness.include: livenessState,diskSpace,ping
  endpoints:
    jmx:
      exposure.include: "*"
    web:
      exposure.include: info, health